name: calory_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  m_widget:
    git:
      url: https://github.com/BlastTea/MWidget.git
      ref: 48e10db703d385043f1e753473b59e2514b4a246
  package_info_plus: ^5.0.1
  path: ^1.8.3
  sqflite: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  image_path: "assets/logo.png"